comment: false
flags:
  unit:
    paths:
      - apps/api/src/
    carryforward: true
  e2e:
    paths:
      - apps/api/src/
    carryforward: true
coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 80%
